branches:
  - master
  - release-drafter  # for testing edits to this configuration

name-template: 'Version $NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

sort-by: title # sort alphabetically
sort-direction: ascending

categories:
  - title: '**ADDED:**'
    labels:
      - 'pr/feature'
  - title: '**FIXED:**'
    labels:
      - 'pr/bug-fix'
  - title: '**IMPROVED:**'
    labels:
      - 'pr/enhancement'
      - 'pr/optimization'
  - title: '**CHANGED:**'
    labels:
      - 'pr/cleanup'
      - 'pr/change'
  - title: '**SETTINGS:**'
    labels:
      - 'pr/setting'
  - title: '**TRANSLATIONS:**'
    labels:
      - 'pr/translation'

exclude-labels:
  - 'ignore-changelog'
  - 'dependencies'

change-template: '- $TITLE (#$NUMBER)'
template: |
  _Requires CBA version X.Y.Z or later and Arma 3 version X.Y or later._

  ## Change Log Summary

  $CHANGES

replacers:
  # Category titles
  - search: '/\#\# (\*\*(ADDED|FIXED|IMPROVED|CHANGED|SETTINGS|TRANSLATIONS):\*\*)/g'
    replace: '$1'