[binarize]
enabled = false # Default: true
exclude = [

]

[rapify]
enabled = false # Default: true
exclude = [
    
]

[files]
exclude = [
    ".vscode/**/*", # Exclude all files in the .vscode folder
    "data/*.psd",
]
