# Launched with `hemtt launch`
[default]
workshop = [
    "463939057", # ACE3's Workshop ID
    "450814997", # CBA_A3's Workshop ID
    "2369477168", # Advanced Developer Tools' Workshop ID
    "751965892", #  ACRE's Workshop ID
    "3018767334", # Open in VS Code Workshop ID
    "3023395342", # 3DEN Attributes Fast Load Workshop ID

]
#optionals = []
#mission = "test.VR" # Mission to launch directly into the editor with
parameters = [
    "-world=empty",
]
mission = "ttt_test.VR"

#executable = "arma3_x64" # Default: "arma3_x64"
#file_patching = true # Default: true
#binarize = false # Default: false
#rapify = true # Default: true

# Launched with `hemtt launch cup/rhs/bwa`
[cup]
extends = "default"
workshop = [
    "497660133", # CUP Weapons Workshop ID
    "541888371", # CUP Vehicles Workshop ID
    "497661914", # CUP Units Workshop ID
    "1369691841", # CFP Workshop ID
]

[rhs]
extends = "default"
workshop = [
    "843425103", # RHS AFRF Workshop ID
    "843577117", # RHS USAF Workshop ID
    "843593391", # RHS GREF Workshop ID
    "843632231", # RHS SAF  Workshop ID
]

[bwa3]
extends = "cup"
workshop = [
    "1200127537", # BWmod Workshop ID
]
