name = "TTT-Mod"
author = "Tactical Training Team"
prefix = "ttt"
mainprefix = "z"

[version]
major = 3 # Overrides path when set
minor = 0
patch = 0
build = 0 # Optional

git_hash = 8 # Default: 8

[files]
exclude = [
    "*.psd",
    "*.png",
    "*.tga",
    "teleporter"
]
include = [
    "meta.cpp", 
    "mod.cpp", 
    "authors.txt", 
    "LICENSE", 
    "*.paa",
]

[lints.sqf]
command_case = true

[properties]
url = "https://github.com/Andx667/TTT-Mod"

[hemtt.signing]
authority = "Tactical Training Team"
