name = "Andx Mod"
author = "Andx"
prefix = "andx"
mainprefix = "z"

[version]
major = 0 # Overrides path when set
minor = 1
patch = 0
build = 1 # Optional

git_hash = 8 # Default: 8

[lints.sqf]
command_case = false

[properties]
url = "https://github.com/Andx667/Andx-Mod"

