name = "TTT-Mod"
author = "Tactical Training Team"
prefix = "ttt"
mainprefix = "z"

[files]
exclude = [
    "*.psd",
    "*.png",
    "*.tga",
    "teleporter"
]
include = [
    "meta.cpp", 
    "mod.cpp", 
    "authors.txt", 
    "LICENSE", 
    "*.paa",
]

[lints.sqf]
command_case = true

[properties]
url = "https://github.com/Andx667/TTT-Mod"

[hemtt.signing]
authority = "Tactical Training Team"
